env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-essential
  - plugin:@typescript-eslint/recommended
overrides: []
parser: 'vue-eslint-parser'
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  eol-last:
    - error
    - always
  no-multi-spaces:
    - error
  no-multiple-empty-lines:
    - error
    - max: 2
  object-property-newline:
    - error
    -
      allowAllPropertiesOnSameLine: false
  no-trailing-spaces:
    - error
  object-curly-newline:
    - error
    -
      ObjectExpression:
        multiline: true
        minProperties: 1
      ObjectPattern:
        multiline: true
        minProperties: 1
      ImportDeclaration:
        multiline: true
        minProperties: 1
      ExportDeclaration:
        multiline: true
        minProperties: 1
  object-curly-spacing:
    - error
    - always
  keyword-spacing:
    - error
    -
      before: true
      after: true
  no-whitespace-before-property:
    - error
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: false
  comma-dangle:
    - error
    - always-multiline
  quotes:
    - error
    - single
  semi:
    - error
    - never
  arrow-parens:
    - error
    - always
  block-spacing:
    - error
    - always
  arrow-spacing:
    - error
    - 
      before: true
      after: true
  'vue/multi-word-component-names': off
ignorePatterns:
  - '*.json'
  - 'dist/*'
  - 'content/*'
